snowflake:
  target: dev
  outputs:
    dev:
      type: bigquery
      project: "{{ env_var('BIGQUERY_PROJECT') }}"
      method: service-account
      schema: "{{ env_var('DBT_SCHEMA') }}"
      keyfile: .creds/creds.json
      threads: 8